### ISSUE TITLE
Открытие модуля команд объектов

### ISSUE THREAD

**Issue by nixel2007** [zerobig/vscode-1c-metadata-viewer#14]
При вызове открытия модуля команды объекта формируется неверный путь к файлу bsl

![image](https://user-images.githubusercontent.com/1132840/200259587-87a74487-e3eb-43f4-afde-b9190bfdf318.png)

**Comment by nixel2007** [comment]
Кажется, имя объекта-владельца не вырезается из полного имени объекта метаданных

**Comment by zerobig** [comment]
Исправил a586c642c8c985cf8a90b1f4d6c955b4d5294d79
Войдет в версию 0.0.7
