### ISSUE TITLE
Открытие configuration.xml

### ISSUE THREAD

**Issue by Segate-ekb** [zerobig/vscode-1c-metadata-viewer#17]
При выборе "Открыть xml" на корне конфигурации я ожидаю, что откроется configuration.xml

Но возникает следующая ошибка:
![image](https://user-images.githubusercontent.com/80944823/205564861-1692f686-e001-4339-a763-3303487465ab.png)

**Comment by zerobig** [comment]
Спасибо за сообщение об ошибке!
Правка bacb65e06c2ffa1ddb0dac0e722dfbc71629fa38 войдёт в 0.0.10
