### ISSUE TITLE
Открытие xml формы объекта

### ISSUE THREAD

**Issue by Segate-ekb** [zerobig/vscode-1c-metadata-viewer#18]
На данный момент при открытии xml формы объекта открывается файл .../<объект>/forms/<ИмяФормы>.xml
Что в целом конечно правильно, но в 99% случаев я, открывая xml формы, жажду увидеть не ее имплементацию в объект, а саму форму, т.е. ../<объект>/forms/<ИмяФормы>/form.xml

Предлагаю изменить поведение.

**Comment by zerobig** [comment]
Не совсем понял.
Может быть имеется в виду ../<Объект>/Forms/<ИмяФормы>/Ext/Form.xml?
Второй вопрос... Текущее поведение совсем не нужно? Или сделать два пункта для двух XML?

**Comment by zerobig** [comment]
Ок. На неделе займусь.

**Comment by zerobig** [comment]
210bfdf5e1d71969c4368351bd472c9dfb03f8e5
