### ISSUE TITLE
Не видит модули форм объектов

### ISSUE THREAD

**Issue by EvilBeaver** [zerobig/vscode-1c-metadata-viewer#19]
![image](https://github.com/zerobig/vscode-1c-metadata-viewer/assets/2657561/d8d88e0c-97b7-4d46-8fbc-60f618f37f3f)

При попытке открыть модуль формы ругается, что такого файла нет. В то время, как он есть.

**Comment by zerobig** [comment]
@EvilBeaver Спасибо за ваше сообщение!
Посмотрю на выходных. Проблемы с личным временем хронические...

**Comment by zerobig** [comment]
Вроде бы исправил. e839683ccbde396bde7ab5eccd312fcadf94e5eb
Надеюсь ничего не сломал. Надо бы тесты завести...
