### ISSUE TITLE
Параметр для указания пути к корню конфигурации

### ISSUE THREAD

**Issue by nixel2007** [zerobig/vscode-1c-metadata-viewer#2]
Сейчас дерево строится прямо от workspaceFolder[0]. Часто помимо собственно исходников в репе лежат еще и другие файлы и папки, а исходники выведены в src или src/cf.

**Comment by zerobig** [comment]
Получилось вот так #13

В конфигурации появился параметр: "Количество уровней вложенности каталогов в которых осуществляется поиск конфигураций 1С:Предприятия" По-умолчанию равен трём.
