### ISSUE TITLE
Добавить поддержку расширений

### ISSUE THREAD

**Issue by SeiOkami** [zerobig/vscode-1c-metadata-viewer#20]
Предлагаю добавить поддержку расширений

![image](https://github.com/zerobig/vscode-1c-metadata-viewer/assets/42138875/de4536e5-977f-4093-b2d6-a3f1c986167b)

**Comment by zerobig** [comment]
Должно работать. У себя не наблюдаю проблему. Нужно больше информации.
![github#0](https://github.com/zerobig/vscode-1c-metadata-viewer/assets/3147314/57825c86-37f7-4521-a8bf-bbe04276c009)

**Comment by SeiOkami** [comment]
Вот этот проект не понимает: https://github.com/Axial-ERP/interface-parameters-extension

**Comment by zerobig** [comment]
Ошибка когда конфигурация или расширение поддерживает несколько языков.
