### ISSUE TITLE
Ничего не работает

### ISSUE THREAD

**Issue by zipzip332** [zerobig/vscode-1c-metadata-viewer#22]
открываю в vs code папку с выгруженными xml файлами конфигурации, и ниче не происходит, конфигурации пустые, не показывает

**Comment by zipzip332** [comment]
ConfigDumpInfo.xml и Configuration.xml естественно в папке присутствуют

**Comment by zerobig** [comment]
Для расследования ситуации опубликуйте пожалуйста репозиторий с конфигурацией которую вы пытаетесь открыть и добавьте ссылку на этот репозиторий в данном issue.

PS. Постарайтесь впредь воздержаться от применения обсценной лексики в обсуждениях с моим участием.

**Comment by nixel2007** [comment]
> Для расследования ситуации опубликуйте пожалуйста репозиторий с конфигурацией которую вы пытаетесь открыть и добавьте ссылку на этот репозиторий в данном issue.

**Comment by zerobig** [comment]
Решение всего лишь вероятное т.к. данных для теста мне так никто не предоставил. И я ориентировался только на свои представления о порядке событий VS Code.
Войдёт в релиз 0.1.1

**Comment by 7OH** [comment]
Нет возможности закинуть 11 Гиг в гит - бесплатный план не позволяет.
Могу скинуть CF-ники от этих конфигураций на яндекс (ну или выгрузку архивом, если критично - туда же)

**Comment by 7OH** [comment]
https://disk.yandex.ru/d/IX9-eWwA9q7NMg
архивом на яндексе - в папке выгрузка 3-х конфижек - возможно чем-то поможет

**Comment by zerobig** [comment]
@7OH @zipzip332 Релиз вышел. Прошу дать обратную связь поданной проблеме.
