### ISSUE TITLE
Фильтрация по подсистемам

### ISSUE THREAD

**Issue by Untru** [zerobig/vscode-1c-metadata-viewer#29]
Прошу рассмотреть такую функциональность, добавить фильтрацию по подсистемам, аналог одноименной функции из конфигуратора. 
Предпосылки: удобная работа только с нужными обьектами и уменьшение времени на скрол.

**Comment by zerobig** [comment]
Принято. Буду думать.

**Comment by zerobig** [comment]
Вроде работает.

**Comment by Untru** [comment]
Лайк
