### ISSUE TITLE
Поддержка формата EDT

### ISSUE THREAD

**Issue by IvanMaslikov** [zerobig/vscode-1c-metadata-viewer#3]
Было бы супер добавить поддержку исходников в формате EDT.

**Comment by zerobig** [comment]
- Сконвертировал базу в формат EDT
- Подождал минут 20 при сильно гудящем кулером компьютере
- Попутно не забываю ужасаться количеству сожранной памяти (Docker забился в угол и нервно курит)
- Посмотрел на результат
- Пошел в коридор ругаться матом (при ребёнке не педагогично)

Вывод: сделать можно. Но сложнее чем с выгрузкой из Конфигуратора. Отсутствует аналог очень удобного файла ConfigDumpInfo.xml в котором собрана почти вся информация для построения дерева.

Взял в работу. Но явно не первоочередная задача. Sorry.

**Comment by nixel2007** [comment]
@zerobig вот поэтому и было предложение с интеграцией с бсл лс, там поддерживаются оба формата сразу :)

**Comment by Daabramov** [comment]
> 1. Запустил конвертацию базы в формат EDT
> 2. Подождал минут 20 при сильно гудящем кулером компьютере
> 3. Попутно не забываю ужасаться количеству сожранной памяти (Docker забился в угол и нервно курит)
> 4. Посмотрел на результат
> 5. Пошел в коридор ругаться матом (при ребёнке не педагогично)
> 
> Вывод: сделать можно. Но сложнее чем с выгрузкой из Конфигуратора. Отсутствует аналог очень удобного файла ConfigDumpInfo.xml в котором собрана почти вся информация для построения дерева.
> 
> Взял в работу. Но явно не первоочередная задача. Sorry.

В папке Configuration есть файлик Configuration.mdo, там почти все тоже есть

**Comment by zerobig** [comment]
> В папке Configuration есть файлик Configuration.mdo, там почти все тоже есть

Подсистемы там только первого уровня...
Наименования форм, команд макетов отсутствуют.
Что-то ещё мне не понравилось. Забыл уже.
Я же говорю, делать буду. Просто не быстро.

**Comment by zerobig** [comment]
#27
