### ISSUE TITLE
Не обрабатывает модуль формы документа

### ISSUE THREAD

**Issue by Existkun** [zerobig/vscode-1c-metadata-viewer#9]
При попытке открыть модуль формы из дерева метаданных, выскакивает сообщение о том, что модуль не существует.
В самом каталоге выгруженной конфигурации модуль существует, и его можно открыть напрямую в vsc.

**Comment by zerobig** [comment]
Исправил [Не открывается модуль формы](https://github.com/zerobig/vscode-1c-metadata-viewer/commit/0cb7ff96863bf8cb6a7db07f2178a882db01b315)

Релиз для marketplace сделаю сегодня к вечеру.
